language: node_js
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn run build
  - yarn test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"